### ISSUE TITLE
Use fs where appropriate in the Leiningen stuff

### ISSUE THREAD

**Issue by Raynes** [ninjudd/clojure-protobuf#12]
Mostly just putting this here to remind me to do it on Monday.

**Comment by kurtharriger** [comment]
I was getting an error running lein protobuf due to missing fs dependency.  I solved it for now by adding :dev-dependencies [[fs "1.0.0"]] to my project.  Not sure if it makes sense to bundle fs into protobuf since this would make fs an extra runtime dependency for downstream projects. Maybe leiningen has or could have a :plugin-dependencies or something to make this a transitive build dependency or something, if nothing else perhaps just add it to the readme.

**Comment by Raynes** [comment]
That's strange. What version of protobuf are you using and what version of Leiningen? It looks like the [0.6.0-beta1](http://clojars.org/repo/protobuf/protobuf/0.6.0-beta1/protobuf-0.6.0-beta1.pom) does have the dependency, so I'm not sure what is going on here. I do see that I apparently forgot to actually push the changes that added the dependency, but it is definitely a dependency in the beta.

As for your other concerns, this doesn't add an extra runtime dependency for your project. If a Leiningen plugin has dependencies, they are put in dev-dependencies.

**Comment by kurtharriger** [comment]
Weird, I'm not sure now. I remember I was getting an exception running lein protobuf about missing fs and after looking into the leiningen plugin I saw fs in the ns delcare and added it to my project... but looking at it now I don't see it anywhere.  I do remember I extracted the leiningen folder from the jar file and moved it to my src/leiningen folder as it didn't seem to find it in the src/clj folder.  Perhaps the jar file on clojars is different?  I gave up shortly after that however as I started having compile errors.  I was originally going to use thrift, but this project looked promising so I thought I would try it, but ended up creating a lein-thrift plugin instead.
